### ISSUE TITLE
Suggestion for examples

### ISSUE THREAD

**Issue by alphapapa** [dfeich/org-listcruncher#1]
Hi there,

I saw your post on /r/emacs, and this is very cool!  One suggestion: the examples would be easier to follow and understand if they were a bit simpler and didn't use abbreviations.  Maybe something like:

```org
+  Shopping list
     -  Foods (type: food)
          +  Fruit (food-type: fruit)
               -  item: banana (color: yellow, cost: 0.50)
               -  item: apple (color: red, cost: 0.25)
          +  Vegetables (food-type: vegetable)
               -  item: carrot (color: orange, cost: 0.20)
               -  item: squash (color: yellow, cost: 0.30)
          +  item: cookies (food-type: dessert, cost: 3.00)
```

**Comment by dfeich** [comment]
Thanks for your suggestion. I guess I have been already consumed by "management-speak"... it does that to you. I adapted the examples.

Cheers!
